### ISSUE TITLE
Implement term help tips

### ISSUE THREAD

**Issue by pjsumm** [ryanhofdotgov/e-QIP-prototype-truetandem#1983]
As an eApp applicant I want to see in-line assistance/help for complex terms so that I can get a better understanding of complex terms without leaving the page.

Acceptance Criteria
- [ ] Follow the design from #1871 
- [ ] Implement framework using term example from the story board
- [ ] Make framework easy to implement across the form

**Comment by bmallred** [comment]
https://www.planitpoker.com/board/#/room/1ff42246ae5a48d684d6e32f1b736b38

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
