### ISSUE TITLE
Review STIG checklist comments

### ISSUE THREAD

**Issue by pjsumm** [ryanhofdotgov/e-QIP-prototype-truetandem#2869]
As an eApp stakeholder I want to review comments on the eApp STIG checklist provided by the eApp security team and respond to the comments so that I can return updated comments to the security team for further review.

Acceptance Criteria:
- [ ] Provide responses to ~50 security team questions
- [ ] Facilitate feedback from infrastructure team
- [ ] Submit result to eApp security team

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
